name: Build Monorepo (Front & Back)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: npm install --prefix front

      - name: Build Frontend
        run: npm run build --prefix front
        env:
          CI: true

      - name: Archive Frontend Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: front/build
          retention-days: 1

      - name: Install Root/Backend Dependencies
        run: npm install

      - name: Create Backend ZIP file
        run: |
          zip -r backend.zip server.js Back/ package.json -x "node_modules/*" ".git/*" ".github/*" ".env*"

      - name: Archive Backend ZIP Artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-zip
          path: backend.zip
          retention-days: 1
